import type { CategoryInfo, ServiceItem, PackageInfo } from "./types";

export const HOSTING_FEE = 50;

export const HOSTING_TRIGGER_IDS = [
  "landing-page",
  "website-1-3-wordpress",
  "website-3-5-wordpress",
  "shopify-setup",
  "woocommerce-setup",
];

export const CATEGORIES: CategoryInfo[] = [
  { id: "strategy", name: "Strategy", name_es: "Estrategia", name_fr: "Stratégie", icon: "\uD83C\uDFAF" },
  { id: "website", name: "Website", name_es: "Sitio Web", name_fr: "Site Web", icon: "\uD83C\uDF10" },
  { id: "ecommerce", name: "Ecommerce", name_es: "Comercio Electrónico", name_fr: "Commerce en Ligne", icon: "\uD83D\uDED2" },
  { id: "social-media", name: "Social Media", name_es: "Redes Sociales", name_fr: "Réseaux Sociaux", icon: "\uD83D\uDCF1" },
  { id: "content", name: "Content", name_es: "Contenido", name_fr: "Contenu", icon: "\u2728" },
  { id: "video-production", name: "Video Production", name_es: "Producción de Video", name_fr: "Production Vidéo", icon: "\uD83C\uDFA5" },
  { id: "email", name: "Email", name_es: "Correo Electrónico", name_fr: "Email", icon: "\uD83D\uDCE7" },
  { id: "seo", name: "SEO", name_es: "SEO", name_fr: "SEO", icon: "\uD83D\uDD0D" },
  { id: "ads", name: "Ads", name_es: "Anuncios", name_fr: "Publicité", icon: "\uD83D\uDCCA" },
  { id: "ai-automation", name: "AI & Automation", name_es: "IA y Automatización", name_fr: "IA et Automatisation", icon: "\uD83E\uDD16" },
];

export const SERVICES: ServiceItem[] = [
  // ── Strategy ──
  {
    id: "brand-audit",
    category: "strategy",
    name: "Brand & Marketing Audit",
    name_es: "Auditoría de Marca y Marketing",
    name_fr: "Audit de Marque et Marketing",
    description: "Deep dive into your current marketing efforts, brand positioning, and competitive landscape. Includes actionable recommendations to improve ROI and messaging consistency.",
    description_es: "Análisis profundo de sus esfuerzos actuales de marketing, posicionamiento de marca y panorama competitivo. Incluye recomendaciones prácticas para mejorar el ROI y la consistencia del mensaje.",
    description_fr: "Analyse approfondie de vos efforts marketing actuels, du positionnement de marque et du paysage concurrentiel. Comprend des recommandations concrètes pour améliorer le ROI et la cohérence des messages.",
    price: 500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "customer-journey",
    category: "strategy",
    name: "Customer Journey Mapping",
    name_es: "Mapeo del Viaje del Cliente",
    name_fr: "Cartographie du Parcours Client",
    description: "Visual documentation of every touchpoint in your customer\u2019s path from awareness to purchase. Identifies gaps and opportunities to improve conversion rates.",
    description_es: "Documentación visual de cada punto de contacto en el camino de su cliente desde el conocimiento hasta la compra. Identifica brechas y oportunidades para mejorar las tasas de conversión.",
    description_fr: "Documentation visuelle de chaque point de contact dans le parcours de votre client, de la découverte à l\u2019achat. Identifie les lacunes et les opportunités pour améliorer les taux de conversion.",
    price: 500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "offer-positioning",
    category: "strategy",
    name: "Offer Positioning & Messaging",
    name_es: "Posicionamiento de Oferta y Mensaje",
    name_fr: "Positionnement d\u2019Offre et Messages",
    description: "Clarify what makes you different and why customers should choose you. Includes core messaging framework, value propositions, and competitive differentiation strategy.",
    description_es: "Aclare qué lo hace diferente y por qué los clientes deberían elegirlo. Incluye marco de mensajes centrales, propuestas de valor y estrategia de diferenciación competitiva.",
    description_fr: "Clarifiez ce qui vous différencie et pourquoi les clients devraient vous choisir. Comprend un cadre de messages clés, des propositions de valeur et une stratégie de différenciation.",
    price: 1000,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "monthly-advisory",
    category: "strategy",
    name: "Monthly Strategy Advisory",
    name_es: "Asesoría Estratégica Mensual",
    name_fr: "Conseil Stratégique Mensuel",
    description: "Ongoing strategic guidance with monthly check-ins. Get expert advice on campaigns, growth opportunities, and marketing decisions as your business evolves.",
    description_es: "Orientación estratégica continua con revisiones mensuales. Obtenga asesoramiento experto sobre campañas, oportunidades de crecimiento y decisiones de marketing a medida que su negocio evoluciona.",
    description_fr: "Accompagnement stratégique continu avec des points mensuels. Conseils d\u2019experts sur les campagnes, les opportunités de croissance et les décisions marketing.",
    price: 500,
    billing: "monthly",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "vip-day",
    category: "strategy",
    name: "VIP Strategy Day",
    name_es: "Día de Estrategia VIP",
    name_fr: "Journée Stratégie VIP",
    description: "Full-day intensive strategy session with our team. Walk away with a complete 90-day marketing roadmap, campaign plans, and clear action steps to accelerate growth.",
    description_es: "Sesión intensiva de estrategia de día completo con nuestro equipo. Salga con una hoja de ruta de marketing completa de 90 días, planes de campaña y pasos de acción claros para acelerar el crecimiento.",
    description_fr: "Session intensive de stratégie d\u2019une journée complète. Repartez avec une feuille de route marketing de 90 jours, des plans de campagne et des étapes d\u2019action claires.",
    price: 3500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },

  // ── Website ──
  {
    id: "landing-page",
    category: "website",
    name: "Landing Page",
    name_es: "Página de Destino",
    name_fr: "Page d\u2019Atterrissage",
    description: "Single high-converting landing page optimized for one specific offer or campaign. Includes copywriting, design, mobile optimization, and basic SEO.",
    description_es: "Una sola página de destino de alta conversión optimizada para una oferta o campaña específica. Incluye redacción, diseño, optimización móvil y SEO básico.",
    description_fr: "Page d\u2019atterrissage unique à fort taux de conversion optimisée pour une offre ou campagne spécifique. Comprend rédaction, design, optimisation mobile et SEO de base.",
    price: 100,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: true,
    note: "All websites include $50/month for hosting and domain fees",
    note_es: "Todos los sitios web incluyen $50/mes por alojamiento y tarifas de dominio",
    note_fr: "Tous les sites web incluent 50$/mois pour l\u2019hébergement et le domaine",
  },
  {
    id: "website-1-3-wordpress",
    category: "website",
    name: "1\u20133 Page Website (WordPress)",
    name_es: "Sitio Web de 1\u20133 Páginas (WordPress)",
    name_fr: "Site Web 1\u20133 Pages (WordPress)",
    description: "Professional WordPress website with up to 3 pages. Includes custom design, copywriting, mobile optimization, basic SEO setup, and analytics integration.",
    description_es: "Sitio web profesional de WordPress con hasta 3 páginas. Incluye diseño personalizado, redacción, optimización móvil, configuración básica de SEO e integración de análisis.",
    description_fr: "Site web WordPress professionnel jusqu\u2019à 3 pages. Comprend design personnalisé, rédaction, optimisation mobile, configuration SEO de base et intégration analytique.",
    price: 500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: true,
    note: "All websites include $50/month for hosting and domain fees",
    note_es: "Todos los sitios web incluyen $50/mes por alojamiento y tarifas de dominio",
    note_fr: "Tous les sites web incluent 50$/mois pour l\u2019hébergement et le domaine",
  },
  {
    id: "website-3-5-wordpress",
    category: "website",
    name: "3\u20135 Page Website (WordPress)",
    name_es: "Sitio Web de 3\u20135 Páginas (WordPress)",
    name_fr: "Site Web 3\u20135 Pages (WordPress)",
    description: "Comprehensive WordPress website with up to 5 pages. Includes advanced features, blog setup, contact forms, and full SEO optimization.",
    description_es: "Sitio web integral de WordPress con hasta 5 páginas. Incluye funciones avanzadas, configuración de blog, formularios de contacto y optimización SEO completa.",
    description_fr: "Site web WordPress complet jusqu\u2019à 5 pages. Comprend fonctionnalités avancées, configuration de blog, formulaires de contact et optimisation SEO complète.",
    price: 1500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: true,
    note: "All websites include $50/month for hosting and domain fees",
    note_es: "Todos los sitios web incluyen $50/mes por alojamiento y tarifas de dominio",
    note_fr: "Tous les sites web incluent 50$/mois pour l\u2019hébergement et le domaine",
  },
  {
    id: "additional-page",
    category: "website",
    name: "Additional Page",
    name_es: "Página Adicional",
    name_fr: "Page Supplémentaire",
    description: "Add extra pages to your existing website. Each page includes custom design, copywriting, and SEO optimization to match your site\u2019s existing style.",
    description_es: "Agregue páginas adicionales a su sitio web existente. Cada página incluye diseño personalizado, redacción y optimización SEO.",
    description_fr: "Ajoutez des pages supplémentaires à votre site web existant. Chaque page comprend design personnalisé, rédaction et optimisation SEO.",
    price: 100,
    billing: "one-time",
    quantifiable: true,
    triggersHosting: false,
  },
  {
    id: "website-maintenance",
    category: "website",
    name: "Website Maintenance & Updates",
    name_es: "Mantenimiento y Actualizaciones Web",
    name_fr: "Maintenance et Mises à Jour Web",
    description: "Monthly technical support, security updates, plugin updates, content changes, and performance monitoring. Includes up to 2 hours of updates per month.",
    description_es: "Soporte técnico mensual, actualizaciones de seguridad, actualizaciones de complementos, cambios de contenido y monitoreo del rendimiento. Incluye hasta 2 horas de actualizaciones por mes.",
    description_fr: "Support technique mensuel, mises à jour de sécurité, mises à jour de plugins, modifications de contenu et suivi des performances. Comprend jusqu\u2019à 2 heures de mises à jour par mois.",
    price: 200,
    billing: "monthly",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "website-hosting",
    category: "website",
    name: "Website Hosting & Domain",
    name_es: "Hospedaje Web y Dominio",
    name_fr: "Hébergement Web et Domaine",
    description: "Professional hosting with 99.9% uptime, SSL certificate, daily backups, and domain registration/renewal. Required for all websites we build.",
    description_es: "Alojamiento profesional con 99.9% de tiempo de actividad, certificado SSL, copias de seguridad diarias y registro/renovación de dominio.",
    description_fr: "Hébergement professionnel avec 99,9% de disponibilité, certificat SSL, sauvegardes quotidiennes et enregistrement/renouvellement de domaine.",
    price: 50,
    billing: "monthly",
    quantifiable: false,
    triggersHosting: false,
  },

  // ── Ecommerce ──
  {
    id: "shopify-setup",
    category: "ecommerce",
    name: "Shopify Store Setup",
    name_es: "Configuración de Tienda Shopify",
    name_fr: "Configuration Boutique Shopify",
    description: "Complete Shopify store configuration including theme customization, payment gateway setup, shipping zones, tax settings, and up to 10 products.",
    description_es: "Configuración completa de la tienda Shopify, incluida la personalización del tema, la configuración de la pasarela de pago, las zonas de envío, la configuración de impuestos y hasta 10 productos.",
    description_fr: "Configuration complète de boutique Shopify incluant la personnalisation du thème, la passerelle de paiement, les zones d\u2019expédition, les paramètres fiscaux et jusqu\u2019à 10 produits.",
    price: 1500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: true,
    note: "All websites include $50/month for hosting and domain fees",
    note_es: "Todos los sitios web incluyen $50/mes por alojamiento y tarifas de dominio",
    note_fr: "Tous les sites web incluent 50$/mois pour l\u2019hébergement et le domaine",
  },
  {
    id: "woocommerce-setup",
    category: "ecommerce",
    name: "WooCommerce Store Setup (WordPress)",
    name_es: "Configuración de Tienda WooCommerce (WordPress)",
    name_fr: "Configuration Boutique WooCommerce (WordPress)",
    description: "Full WooCommerce store on WordPress including theme setup, payment processing, shipping configuration, and up to 10 products.",
    description_es: "Tienda WooCommerce completa en WordPress que incluye configuración de temas, procesamiento de pagos, configuración de envío y hasta 10 productos.",
    description_fr: "Boutique WooCommerce complète sur WordPress incluant la configuration du thème, le traitement des paiements, la configuration d\u2019expédition et jusqu\u2019à 10 produits.",
    price: 1500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: true,
    note: "All websites include $50/month for hosting and domain fees",
    note_es: "Todos los sitios web incluyen $50/mes por alojamiento y tarifas de dominio",
    note_fr: "Tous les sites web incluent 50$/mois pour l\u2019hébergement et le domaine",
  },
  {
    id: "product-upload",
    category: "ecommerce",
    name: "Product Upload & Formatting",
    name_es: "Carga y Formato de Productos",
    name_fr: "Mise en Ligne et Formatage de Produits",
    description: "Professional product listing with optimized images, SEO-friendly descriptions, pricing, variants, and inventory setup. Price is per product.",
    description_es: "Listado profesional de productos con imágenes optimizadas, descripciones amigables con SEO, precios, variantes y configuración de inventario. El precio es por producto.",
    description_fr: "Listing professionnel de produits avec images optimisées, descriptions SEO, prix, variantes et configuration d\u2019inventaire. Prix par produit.",
    price: 50,
    billing: "one-time",
    quantifiable: true,
    unit: "product",
    unit_es: "producto",
    unit_fr: "produit",
    triggersHosting: false,
  },
  {
    id: "product-optimization",
    category: "ecommerce",
    name: "Product Page Optimization",
    name_es: "Optimización de Página de Producto",
    name_fr: "Optimisation de Page Produit",
    description: "Conversion-focused optimization of existing product pages. Includes A/B testing recommendations, enhanced descriptions, better images, and SEO improvements.",
    description_es: "Optimización centrada en la conversión de páginas de productos existentes. Incluye recomendaciones de pruebas A/B, descripciones mejoradas, mejores imágenes y mejoras de SEO.",
    description_fr: "Optimisation axée sur la conversion des pages produits existantes. Comprend recommandations de tests A/B, descriptions améliorées et optimisations SEO.",
    price: 75,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "collection-page",
    category: "ecommerce",
    name: "Collection/Category Page Setup",
    name_es: "Configuración de Página de Colección/Categoría",
    name_fr: "Configuration de Page Collection/Catégorie",
    description: "Organized product collections with filtering, sorting, and optimized layouts. Includes SEO optimization for category pages.",
    description_es: "Colecciones de productos organizadas con filtrado, clasificación y diseños optimizados. Incluye optimización SEO para páginas de categoría.",
    description_fr: "Collections de produits organisées avec filtrage, tri et mises en page optimisées. Comprend l\u2019optimisation SEO pour les pages de catégorie.",
    price: 200,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },

  // ── Social Media ──
  {
    id: "social-1-platform",
    category: "social-media",
    name: "Social Management (1 platform)",
    name_es: "Gestión Social (1 plataforma)",
    name_fr: "Gestion Sociale (1 plateforme)",
    description: "Full management of one social platform. Includes 6-8 posts per month, content calendar, caption writing, hashtag research, and monthly analytics reporting.",
    description_es: "Gestión completa de una plataforma social. Incluye 6-8 publicaciones por mes, calendario de contenido, redacción de subtítulos, investigación de hashtags e informes analíticos mensuales.",
    description_fr: "Gestion complète d\u2019une plateforme sociale. Comprend 6-8 publications par mois, calendrier de contenu, rédaction de légendes, recherche de hashtags et rapports analytiques mensuels.",
    price: 750,
    billing: "monthly",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "additional-platform",
    category: "social-media",
    name: "Additional Social Platform",
    name_es: "Plataforma Social Adicional",
    name_fr: "Plateforme Sociale Supplémentaire",
    description: "Add another social media platform to your package. Each additional platform includes 6-8 posts per month with coordinated messaging across all your channels.",
    description_es: "Agregue otra plataforma de redes sociales a su paquete. Cada plataforma adicional incluye 6-8 publicaciones por mes con mensajes coordinados en todos sus canales.",
    description_fr: "Ajoutez une autre plateforme de réseaux sociaux à votre forfait. Chaque plateforme supplémentaire comprend 6-8 publications par mois avec des messages coordonnés.",
    price: 500,
    billing: "monthly",
    quantifiable: true,
    triggersHosting: false,
  },
  {
    id: "community-management",
    category: "social-media",
    name: "Community Management",
    name_es: "Gestión de Comunidad",
    name_fr: "Gestion de Communauté",
    description: "Daily monitoring of your comments and DMs. We engage with your audience, answer questions, and foster community growth.",
    description_es: "Monitoreo diario de sus comentarios y mensajes directos. Interactuamos con su audiencia, respondemos preguntas y fomentamos el crecimiento de la comunidad.",
    description_fr: "Suivi quotidien de vos commentaires et messages privés. Nous engageons votre audience, répondons aux questions et favorisons la croissance de la communauté.",
    price: 500,
    billing: "monthly",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "social-strategy",
    category: "social-media",
    name: "Social Media Strategy",
    name_es: "Estrategia de Redes Sociales",
    name_fr: "Stratégie Réseaux Sociaux",
    description: "Comprehensive strategy document covering content pillars, visual direction, hashtag strategy, and engagement tactics.",
    description_es: "Documento de estrategia integral que cubre pilares de contenido, dirección visual, estrategia de hashtags y tácticas de compromiso.",
    description_fr: "Document de stratégie complet couvrant les piliers de contenu, la direction visuelle, la stratégie de hashtags et les tactiques d\u2019engagement.",
    price: 600,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },

  // ── Content ──
  {
    id: "static-post",
    category: "content",
    name: "Static Post Design",
    name_es: "Diseño de Publicación Estática",
    name_fr: "Design de Publication Statique",
    description: "Single-image social media post with professional design, on-brand graphics, and compelling copy. Delivered in all required sizes.",
    description_es: "Publicación de redes sociales de una sola imagen con diseño profesional, gráficos de marca y copia convincente. Entregado en todos los tamaños requeridos.",
    description_fr: "Publication de réseau social en image unique avec design professionnel, graphismes de marque et texte convaincant. Livrée dans tous les formats requis.",
    price: 50,
    billing: "one-time",
    quantifiable: true,
    triggersHosting: false,
  },
  {
    id: "carousel",
    category: "content",
    name: "Carousel Design",
    name_es: "Diseño de Carrusel",
    name_fr: "Design de Carrousel",
    description: "Multi-slide carousel post (up to 10 slides) for Instagram, Facebook, or LinkedIn. Includes design and copywriting.",
    description_es: "Publicación de carrusel de múltiples diapositivas (hasta 10 diapositivas) para Instagram, Facebook o LinkedIn. Incluye diseño y redacción.",
    description_fr: "Publication carrousel multi-diapositives (jusqu\u2019à 10 diapositives) pour Instagram, Facebook ou LinkedIn. Comprend design et rédaction.",
    price: 100,
    billing: "one-time",
    quantifiable: true,
    triggersHosting: false,
  },
  {
    id: "reel-edit",
    category: "content",
    name: "Reel / Short-Form Video Edit",
    name_es: "Edición de Reel / Video de Formato Corto",
    name_fr: "Montage Reel / Vidéo Courte",
    description: "Professional editing of short-form video content (15-60 seconds) for Instagram Reels, TikTok, or YouTube Shorts. Includes cuts, transitions, captions, music, and brand elements.",
    description_es: "Edición profesional de contenido de video de formato corto (15-60 segundos) para Instagram Reels, TikTok o YouTube Shorts. Incluye cortes, transiciones, subtítulos, música y elementos de marca.",
    description_fr: "Montage professionnel de vidéo courte (15-60 secondes) pour Instagram Reels, TikTok ou YouTube Shorts. Comprend coupes, transitions, sous-titres, musique et éléments de marque.",
    price: 125,
    billing: "one-time",
    quantifiable: true,
    triggersHosting: false,
  },
  {
    id: "blog-writing",
    category: "content",
    name: "SEO Blog Post (1000 words)",
    name_es: "Publicación de Blog SEO (1000 palabras)",
    name_fr: "Article de Blog SEO (1000 mots)",
    description: "High-quality, SEO-optimized blog article. Includes keyword research, internal linking, and meta description.",
    description_es: "Artículo de blog de alta calidad, optimizado para SEO. Incluye investigación de palabras clave, enlaces internos y meta descripción.",
    description_fr: "Article de blog de haute qualité optimisé pour le SEO. Comprend recherche de mots-clés, liens internes et méta description.",
    price: 250,
    billing: "one-time",
    quantifiable: true,
    triggersHosting: false,
  },
  {
    id: "website-copy",
    category: "content",
    name: "Website Copywriting (Per Page)",
    name_es: "Redacción de Sitios Web (Por Página)",
    name_fr: "Rédaction Web (Par Page)",
    description: "Conversion-focused copy for your main website pages. Compelling messaging that guides visitors to take action.",
    description_es: "Copia centrada en la conversión para sus páginas principales del sitio web. Mensajes convincentes que guían a los visitantes a tomar medidas.",
    description_fr: "Rédaction axée sur la conversion pour vos pages web principales. Messages convaincants qui guident les visiteurs vers l\u2019action.",
    price: 300,
    billing: "one-time",
    quantifiable: true,
    triggersHosting: false,
  },

  // ── Video Production ──
  {
    id: "brand-video",
    category: "video-production",
    name: "Brand Story Video",
    name_es: "Video de Historia de Marca",
    name_fr: "Vidéo d\u2019Histoire de Marque",
    description: "Cinematic main video for your website homepage (60-90 seconds). Coverage of your business, interview with founder, and professional voiceover/music.",
    description_es: "Video principal cinematográfico para la página de inicio de su sitio web (60-90 segundos). Cobertura de su negocio, entrevista con el fundador y voz en off / música profesional.",
    description_fr: "Vidéo principale cinématographique pour votre page d\u2019accueil (60-90 secondes). Couverture de votre entreprise, interview du fondateur et voix off/musique professionnelle.",
    price: 2500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "testimonial-video",
    category: "video-production",
    name: "Testimonial Video",
    name_es: "Video Testimonial",
    name_fr: "Vidéo Témoignage",
    description: "Interview-style video with a happy client. Builds social proof. Includes filming, editing, and b-roll.",
    description_es: "Video estilo entrevista con un cliente feliz. Construye prueba social. Incluye filmación, edición y b-roll.",
    description_fr: "Vidéo style interview avec un client satisfait. Renforce la preuve sociale. Comprend tournage, montage et plans de coupe.",
    price: 1200,
    billing: "one-time",
    quantifiable: true,
    triggersHosting: false,
  },
  {
    id: "shoot-half-day",
    category: "video-production",
    name: "On-Site Shoot (Half Day)",
    name_es: "Sesión en el Sitio (Medio Día)",
    name_fr: "Tournage sur Site (Demi-Journée)",
    description: "4-hour professional video/photo shoot at your location. Perfect for social media content, team headshots, or product b-roll.",
    description_es: "Sesión profesional de video / fotos de 4 horas en su ubicación. Perfecto para contenido de redes sociales, fotos del equipo o b-roll del producto.",
    description_fr: "Tournage professionnel vidéo/photo de 4 heures sur votre lieu. Idéal pour le contenu réseaux sociaux, les photos d\u2019équipe ou les plans de coupe produits.",
    price: 1000,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "shoot-full-day",
    category: "video-production",
    name: "On-Site Shoot (Full Day)",
    name_es: "Sesión en el Sitio (Día Completo)",
    name_fr: "Tournage sur Site (Journée Complète)",
    description: "8-hour comprehensive shoot day. Multiple interviews, extensive b-roll, and multiple locations if needed.",
    description_es: "Día de sesión completo de 8 horas. Múltiples entrevistas, extenso b-roll y múltiples ubicaciones si es necesario.",
    description_fr: "Journée complète de tournage de 8 heures. Multiples interviews, plans de coupe étendus et multiples lieux si nécessaire.",
    price: 1800,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "video-editing",
    category: "video-production",
    name: "Long-Form Video Editing",
    name_es: "Edición de Video de Formato Largo",
    name_fr: "Montage Vidéo Long Format",
    description: "Professional editing for YouTube videos, webinars, or course content (up to 15 mins). Includes color grading, sound mixing, motion graphics, and captions.",
    description_es: "Edición profesional para videos de YouTube, seminarios web o contenido del curso (hasta 15 minutos). Incluye gradación de color, mezcla de sonido, gráficos en movimiento y subtítulos.",
    description_fr: "Montage professionnel pour vidéos YouTube, webinaires ou contenu de formation (jusqu\u2019à 15 min). Comprend étalonnage, mixage sonore, motion graphics et sous-titres.",
    price: 350,
    billing: "one-time",
    quantifiable: true,
    triggersHosting: false,
  },
  {
    id: "podcast-episode",
    category: "video-production",
    name: "Podcast Episode Production",
    name_es: "Producción de Episodio de Podcast",
    name_fr: "Production d\u2019Épisode de Podcast",
    description: "Professional audio/video production for one podcast episode. Includes cleaning, mixing, intro/outro editing, and show notes.",
    description_es: "Producción de audio / video profesional para un episodio de podcast. Incluye limpieza, mezcla, edición de intro / outro y notas del programa.",
    description_fr: "Production audio/vidéo professionnelle pour un épisode de podcast. Comprend nettoyage, mixage, montage intro/outro et notes de l\u2019émission.",
    price: 250,
    billing: "one-time",
    quantifiable: true,
    triggersHosting: false,
  },

  // ── Email ──
  {
    id: "newsletter",
    category: "email",
    name: "Newsletter Creation",
    name_es: "Creación de Boletines",
    name_fr: "Création de Newsletter",
    description: "Professionally designed and written email newsletter. Includes subject line, preview text, engaging content, and call-to-action.",
    description_es: "Boletín de correo electrónico diseñado y escrito profesionalmente. Incluye línea de asunto, texto de vista previa, contenido atractivo y llamado a la acción.",
    description_fr: "Newsletter email conçue et rédigée professionnellement. Comprend ligne d\u2019objet, texte de prévisualisation, contenu engageant et appel à l\u2019action.",
    price: 125,
    billing: "monthly",
    quantifiable: true,
    unit: "Emails Per Month",
    unit_es: "Correos por Mes",
    unit_fr: "Emails par Mois",
    triggersHosting: false,
  },
  {
    id: "promo-email",
    category: "email",
    name: "Promo Email Blast",
    name_es: "Envío de Correo Promocional",
    name_fr: "Envoi d\u2019Email Promotionnel",
    description: "Single promotional email designed to drive sales or registrations. Includes strategy, copywriting, design, and list segmentation.",
    description_es: "Un solo correo electrónico promocional diseñado para impulsar ventas o registros. Incluye estrategia, redacción, diseño y segmentación de listas.",
    description_fr: "Email promotionnel unique conçu pour stimuler les ventes ou les inscriptions. Comprend stratégie, rédaction, design et segmentation de liste.",
    price: 125,
    billing: "monthly",
    quantifiable: true,
    unit: "Emails Per Month",
    unit_es: "Correos por Mes",
    unit_fr: "Emails par Mois",
    triggersHosting: false,
  },
  {
    id: "email-sequence",
    category: "email",
    name: "Email Sequence (3\u20135 emails)",
    name_es: "Secuencia de Correo Electrónico (3\u20135 correos)",
    name_fr: "Séquence d\u2019Emails (3\u20135 emails)",
    description: "Automated email nurture sequence with 3-5 emails. Perfect for welcome series, lead nurturing, or post-purchase follow-up.",
    description_es: "Secuencia automatizada de crianza de correo electrónico con 3-5 correos electrónicos. Perfecto para series de bienvenida, crianza de clientes potenciales o seguimiento posterior a la compra.",
    description_fr: "Séquence automatisée de nurturing de 3-5 emails. Idéal pour les séries de bienvenue, le nurturing de prospects ou le suivi post-achat.",
    price: 750,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "email-template",
    category: "email",
    name: "Custom Email Template",
    name_es: "Plantilla de Correo Electrónico Personalizada",
    name_fr: "Modèle d\u2019Email Personnalisé",
    description: "Reusable, branded email template for specific platforms (Mailchimp, Klaviyo, ActiveCampaign). Drag-and-drop ready.",
    description_es: "Plantilla de correo electrónico reutilizable y de marca para plataformas específicas (Mailchimp, Klaviyo, ActiveCampaign). Listo para arrastrar y soltar.",
    description_fr: "Modèle d\u2019email réutilisable et de marque pour des plateformes spécifiques (Mailchimp, Klaviyo, ActiveCampaign). Prêt à l\u2019emploi.",
    price: 300,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "list-cleaning",
    category: "email",
    name: "List Hygiene & Segmentation",
    name_es: "Higiene y Segmentación de Listas",
    name_fr: "Hygiène et Segmentation de Liste",
    description: "Clean up your email list to improve deliverability. Remove bounces, segment active vs inactive subscribers, and organize your database.",
    description_es: "Limpie su lista de correo electrónico para mejorar la capacidad de entrega. Eliminamos rebotes, segmentamos suscriptores activos frente a inactivos y organizamos su base de datos.",
    description_fr: "Nettoyez votre liste email pour améliorer la délivrabilité. Suppression des rebonds, segmentation des abonnés actifs et inactifs, et organisation de votre base de données.",
    price: 250,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },

  // ── SEO ──
  {
    id: "seo-audit",
    category: "seo",
    name: "SEO Audit",
    name_es: "Auditoría SEO",
    name_fr: "Audit SEO",
    description: "Comprehensive technical and content SEO analysis of your website. Includes keyword research, competitor analysis, technical issues, and prioritized action plan.",
    description_es: "Análisis integral de SEO técnico y de contenido de su sitio web. Incluye investigación de palabras clave, análisis de la competencia, problemas técnicos y plan de acción priorizado.",
    description_fr: "Analyse SEO technique et de contenu complète de votre site web. Comprend recherche de mots-clés, analyse concurrentielle, problèmes techniques et plan d\u2019action priorisé.",
    price: 500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "ongoing-seo",
    category: "seo",
    name: "Ongoing SEO",
    name_es: "SEO Continuo",
    name_fr: "SEO Continu",
    description: "Monthly SEO optimization including on-page improvements, content optimization, technical fixes, backlink building, and performance tracking.",
    description_es: "Optimización SEO mensual que incluye mejoras en la página, optimización de contenido, correcciones técnicas, construcción de backlinks y seguimiento del rendimiento.",
    description_fr: "Optimisation SEO mensuelle incluant améliorations on-page, optimisation de contenu, corrections techniques, création de backlinks et suivi des performances.",
    price: 750,
    billing: "monthly",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "local-seo",
    category: "seo",
    name: "Local SEO Setup",
    name_es: "Configuración de SEO Local",
    name_fr: "Configuration SEO Local",
    description: "Optimization of Google Business Profile, local citations, and directory listings. Critical for local service providers.",
    description_es: "Optimización del Perfil de Negocio de Google, citas locales y listados de directorio. Crítico para proveedores de servicios locales.",
    description_fr: "Optimisation du Profil Google Business, citations locales et inscriptions dans les annuaires. Essentiel pour les prestataires de services locaux.",
    price: 400,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "keyword-research",
    category: "seo",
    name: "Deep-Dive Keyword Research",
    name_es: "Investigación Profunda de Palabras Clave",
    name_fr: "Recherche Approfondie de Mots-Clés",
    description: "Extensive research to identify high-potential keywords your competitors are missing. Delivered as a strategy document with content topics and difficulty scores.",
    description_es: "Investigación extensa para identificar palabras clave de alto potencial que sus competidores se están perdiendo. Entregado como un documento de estrategia integral.",
    description_fr: "Recherche approfondie pour identifier les mots-clés à fort potentiel que vos concurrents manquent. Livré sous forme de document stratégique avec sujets de contenu et scores de difficulté.",
    price: 350,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },

  // ── Ads ──
  {
    id: "ad-management",
    category: "ads",
    name: "Monthly Ad Management (1 platform)",
    name_es: "Gestión Mensual de Anuncios (1 plataforma)",
    name_fr: "Gestion Mensuelle de Publicité (1 plateforme)",
    description: "Full ad campaign management on Meta or Google Ads. Includes strategy, ad creation, targeting, budget optimization, A/B testing, and monthly reporting. Ad spend not included.",
    description_es: "Gestión completa de campañas publicitarias en Meta o Google Ads. Incluye estrategia, creación de anuncios, orientación, optimización de presupuesto, pruebas A/B e informes mensuales. Gasto publicitario no incluido.",
    description_fr: "Gestion complète de campagnes publicitaires sur Meta ou Google Ads. Comprend stratégie, création d\u2019annonces, ciblage, optimisation budgétaire, tests A/B et rapports mensuels. Budget publicitaire non inclus.",
    price: 750,
    billing: "monthly",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "ad-creative",
    category: "ads",
    name: "Ad Creative Package",
    name_es: "Paquete Creativo de Anuncios",
    name_fr: "Pack Créatif Publicitaire",
    description: "Set of 5 high-converting ad visuals and ad copy variations. Designed to stop the scroll and drive clicks.",
    description_es: "Conjunto de 5 imágenes publicitarias de alta conversión y variaciones de copia de anuncios. Diseñado para detener el desplazamiento e impulsar los clics.",
    description_fr: "Ensemble de 5 visuels publicitaires à fort taux de conversion et variations de textes. Conçu pour capter l\u2019attention et générer des clics.",
    price: 400,
    billing: "one-time",
    quantifiable: true,
    triggersHosting: false,
  },
  {
    id: "pixel-setup",
    category: "ads",
    name: "Pixel & Tracking Setup",
    name_es: "Configuración de Pixel y Seguimiento",
    name_fr: "Configuration Pixel et Suivi",
    description: "Professional installation of Meta Pixel, Google Analytics 4, and conversion API. Ensures every click and sale is tracked accurately.",
    description_es: "Instalación profesional de Meta Pixel, Google Analytics 4 y API de conversión. Nos aseguramos de que cada clic y venta se realice un seguimiento preciso.",
    description_fr: "Installation professionnelle du Meta Pixel, Google Analytics 4 et API de conversion. Assure le suivi précis de chaque clic et vente.",
    price: 300,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "retargeting",
    category: "ads",
    name: "Retargeting Campaign Setup",
    name_es: "Configuración de Campaña de Retargeting",
    name_fr: "Configuration Campagne de Retargeting",
    description: "Setup of campaigns to follow visitors who didn\u2019t buy. Includes custom audience creation, ad set configuration, and campaign launch.",
    description_es: "Configuración de campañas específicas para seguir a los visitantes que no compraron. Incluye creación de audiencia personalizada y lanzamiento de campañas.",
    description_fr: "Configuration de campagnes pour suivre les visiteurs qui n\u2019ont pas acheté. Comprend création d\u2019audiences personnalisées et lancement de campagnes.",
    price: 500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },

  // ── AI & Automation ──
  {
    id: "dashboard-basic",
    category: "ai-automation",
    name: "Custom Dashboard (Basic)",
    name_es: "Tablero Personalizado (Básico)",
    name_fr: "Tableau de Bord Personnalisé (Basique)",
    description: "Basic analytics dashboard pulling data from your marketing platforms. Includes key metrics visualization, automated reporting, and monthly insights.",
    description_es: "Tablero de análisis básico que extrae datos de sus plataformas de marketing. Incluye visualización de métricas clave, informes automatizados e información mensual.",
    description_fr: "Tableau de bord analytique basique alimenté par vos plateformes marketing. Comprend visualisation des métriques clés, rapports automatisés et analyses mensuelles.",
    price: 5000,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "dashboard-advanced",
    category: "ai-automation",
    name: "Advanced Dashboard with AI Insights",
    name_es: "Tablero Avanzado con Insights de IA",
    name_fr: "Tableau de Bord Avancé avec IA",
    description: "Advanced analytics dashboard with AI-powered insights, predictive analytics, and automated recommendations. Integrates multiple data sources.",
    description_es: "Tablero de análisis avanzado con información impulsada por IA, análisis predictivo y recomendaciones automatizadas. Integra múltiples fuentes de datos.",
    description_fr: "Tableau de bord analytique avancé avec insights IA, analyses prédictives et recommandations automatisées. Intègre plusieurs sources de données.",
    price: 7500,
    priceMax: 10000,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "ai-agent",
    category: "ai-automation",
    name: "Custom AI Agent",
    name_es: "Agente de IA Personalizado",
    name_fr: "Agent IA Personnalisé",
    description: "Tailored AI automation for your specific business needs. Examples: lead qualification chatbot, customer support automation, content generation assistant.",
    description_es: "Automatización de IA adaptada a sus necesidades comerciales específicas. Ejemplos: chatbot de calificación de clientes potenciales, automatización de atención al cliente.",
    description_fr: "Automatisation IA adaptée à vos besoins spécifiques. Exemples : chatbot de qualification de leads, automatisation du support client, assistant de génération de contenu.",
    price: 3500,
    priceMax: 7500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
  {
    id: "ai-automation",
    category: "ai-automation",
    name: "Marketing Automation Setup",
    name_es: "Configuración de Automatización de Marketing",
    name_fr: "Configuration d\u2019Automatisation Marketing",
    description: "Custom workflow automation to save time and improve efficiency. Examples: automated lead follow-up, social media scheduling, email triggers, CRM integration.",
    description_es: "Automatización de flujo de trabajo personalizado para ahorrar tiempo y mejorar la eficiencia. Ejemplos: seguimiento automatizado de clientes potenciales, programación de redes sociales.",
    description_fr: "Automatisation de workflows personnalisée pour gagner du temps et améliorer l\u2019efficacité. Exemples : suivi automatisé des leads, planification des réseaux sociaux, intégration CRM.",
    price: 2500,
    billing: "one-time",
    quantifiable: false,
    triggersHosting: false,
  },
];

export const PACKAGES: PackageInfo[] = [
  {
    id: "startup",
    name: "Business Startup",
    name_es: "Inicio de Negocio",
    name_fr: "Lancement d\u2019Entreprise",
    tagline: "The essential foundation for new businesses",
    tagline_es: "La base esencial para nuevos negocios",
    tagline_fr: "La base essentielle pour les nouvelles entreprises",
    price: 750,
    description: "Get your business off the ground with a professional brand presence and core marketing assets. Designed for speed, affordability, and impact.",
    description_es: "Haga despegar su negocio con una presencia de marca profesional y activos de marketing básicos. Diseñado para velocidad, asequibilidad e impacto.",
    description_fr: "Lancez votre entreprise avec une présence de marque professionnelle et des actifs marketing essentiels. Conçu pour la rapidité, l\u2019accessibilité et l\u2019impact.",
    features: [
      "Brand & Marketing Audit",
      "Landing Page Setup",
      "Social Media Setup (1 Platform)",
      "Basic SEO Setup",
      "3 Social Media Posts",
    ],
    features_es: [
      "Auditoría de Marca y Marketing",
      "Configuración de Página de Destino",
      "Configuración de Redes Sociales (1 Plataforma)",
      "Configuración Básica de SEO",
      "3 Publicaciones en Redes Sociales",
    ],
    features_fr: [
      "Audit de Marque et Marketing",
      "Configuration de Page d\u2019Atterrissage",
      "Configuration Réseaux Sociaux (1 Plateforme)",
      "Configuration SEO de Base",
      "3 Publications sur les Réseaux Sociaux",
    ],
    serviceIds: ["brand-audit", "landing-page", "social-1-platform", "seo-audit", "static-post"],
  },
  {
    id: "growth",
    name: "Business Growth",
    name_es: "Crecimiento Empresarial",
    name_fr: "Croissance d\u2019Entreprise",
    tagline: "Accelerate your visibility and lead generation",
    tagline_es: "Acelere su visibilidad y generación de leads",
    tagline_fr: "Accélérez votre visibilité et la génération de leads",
    price: 1500,
    popular: true,
    description: "Perfect for businesses ready to scale. Includes a full website, ongoing content creation, and paid ad strategies to drive consistent traffic.",
    description_es: "Perfecto para empresas listas para escalar. Incluye un sitio web completo, creación de contenido continuo y estrategias de anuncios pagados para impulsar tráfico constante.",
    description_fr: "Parfait pour les entreprises prêtes à se développer. Comprend un site web complet, la création de contenu continue et des stratégies publicitaires pour un trafic constant.",
    features: [
      "All Startup Features",
      "5-Page Custom Website",
      "Monthly Social Management (2 Platforms)",
      "Email Marketing Sequence (3 Emails)",
      "Ad Campaign Setup & Management",
      "Monthly Strategy Call",
    ],
    features_es: [
      "Todas las Características de Inicio",
      "Sitio Web Personalizado de 5 Páginas",
      "Gestión Mensual de Redes (2 Plataformas)",
      "Secuencia de Marketing por Email (3 Correos)",
      "Configuración y Gestión de Campañas Publicitarias",
      "Llamada de Estrategia Mensual",
    ],
    features_fr: [
      "Toutes les Fonctionnalités Lancement",
      "Site Web Personnalisé 5 Pages",
      "Gestion Mensuelle Réseaux (2 Plateformes)",
      "Séquence Email Marketing (3 Emails)",
      "Configuration et Gestion de Campagnes Publicitaires",
      "Appel Stratégique Mensuel",
    ],
    serviceIds: [
      "brand-audit", "landing-page", "social-1-platform", "seo-audit", "static-post",
      "website-1-3-wordpress", "additional-platform", "email-sequence", "ad-management", "monthly-advisory",
    ],
  },
  {
    id: "scale",
    name: "Business Scale",
    name_es: "Escala Empresarial",
    name_fr: "Expansion d\u2019Entreprise",
    tagline: "Dominate your market with full-service marketing",
    tagline_es: "Domine su mercado con marketing de servicio completo",
    tagline_fr: "Dominez votre marché avec un marketing à service complet",
    price: 3000,
    description: "The ultimate CMO-in-a-box package. We handle everything from high-end video production to advanced automation and multi-channel domination.",
    description_es: "El paquete definitivo de Director de Marketing. Manejamos todo, desde producción de video de alta gama hasta automatización avanzada y dominación multicanal.",
    description_fr: "Le forfait ultime de directeur marketing externalisé. Nous gérons tout, de la production vidéo haut de gamme à l\u2019automatisation avancée et la domination multicanal.",
    features: [
      "All Growth Features",
      "Advanced E-commerce/Membership Site",
      "Brand Story Video Production",
      "Weekly Blog & Content Creation",
      "Advanced SEO & Backlink Building",
      "Full Automation & CRM Setup",
      "Weekly WIP Meetings",
    ],
    features_es: [
      "Todas las Características de Crecimiento",
      "Sitio Avanzado de Comercio Electrónico/Membresía",
      "Producción de Video de Historia de Marca",
      "Creación Semanal de Blog y Contenido",
      "SEO Avanzado y Construcción de Enlaces",
      "Configuración Completa de Automatización y CRM",
      "Reuniones de Progreso Semanales",
    ],
    features_fr: [
      "Toutes les Fonctionnalités Croissance",
      "Site E-commerce/Adhésion Avancé",
      "Production Vidéo d\u2019Histoire de Marque",
      "Création Hebdomadaire de Blog et Contenu",
      "SEO Avancé et Création de Liens",
      "Configuration Complète Automatisation et CRM",
      "Réunions de Progrès Hebdomadaires",
    ],
    serviceIds: [
      "brand-audit", "landing-page", "social-1-platform", "seo-audit", "static-post",
      "website-1-3-wordpress", "additional-platform", "email-sequence", "ad-management", "monthly-advisory",
      "shopify-setup", "brand-video", "blog-writing", "ongoing-seo", "ai-automation",
    ],
  },
];

// ── Helper Functions ──

export function getServiceById(id: string): ServiceItem | undefined {
  return SERVICES.find((s) => s.id === id);
}

export function getServicesByCategory(category: string): ServiceItem[] {
  return SERVICES.filter((s) => s.category === category);
}

export function needsHostingFee(selectedServiceIds: string[]): boolean {
  return selectedServiceIds.some((id) => HOSTING_TRIGGER_IDS.includes(id));
}
